### ISSUE TITLE
safe-buffer in modern build tools like Vitejs

### ISSUE THREAD

**Issue by mecirmartin** [feross/safe-buffer#30]
Hey, i'm trying to use ViteJs for project. 

Since this is es6 only, the code errors out inside safe-buffer package `Buffer` is undefined here 

<img width="883" alt="Screenshot 2021-04-19 at 11 31 26" src="https://user-images.githubusercontent.com/55835379/115214427-c9a56b80-a102-11eb-9ee3-155f2a133e67.png">

If we included this simple check, this wouldn't error out in ViteJs environment.
<img width="351" alt="Screenshot 2021-04-19 at 11 32 12" src="https://user-images.githubusercontent.com/55835379/115214526-e477e000-a102-11eb-9c37-52c2a0d297fd.png">

Is there any reason not to include check like this? If you would be interested, i could submit PR

**Comment by phiiil** [comment]
Hi @mecirmartin, I have the same issue in Sveltekit (which uses Vite). While trying to debug I noticed than [bn](
https://github.com/indutny/bn.js) also uses Buffer and the initialization is more involved and adapted to a bowser context.
```
  var Buffer;
  try {
    if (typeof window !== 'undefined' && typeof window.Buffer !== 'undefined') {
      Buffer = window.Buffer;
    } else {
      Buffer = require('buffer').Buffer;
    }
  } catch (e) {
  }
```
Please submit your PR, I'm interested.

**Comment by phiiil** [comment]
Adding buffer to node_modules fixed this for me.

`npm i buffer`

No need to change the safe-buffer package.

**Comment by code-lixm** [comment]
I have the same problem in ViteJs

**Comment by hatzz** [comment]
> Adding buffer to node_modules fixed this for me.
> 
> `npm i buffer`
> 
> No need to change the safe-buffer package.

This worked even though i don't know why, thank you so much.

**Comment by JasonGore** [comment]
This should absolutely result in a change in `safe-buffer` package. `buffer` should be declared as a dep by `safe-buffer` in its `package.json` if it requires it. I found this problem when I noticed that our bundled output is using any random version of `buffer` it comes across installed by another dependency, regardless of `buffer` major versioning. This will lead to insidious and hard to troubleshoot and the dep should be declared by `safe-buffer`.

**Comment by Scyks** [comment]
I suddenly faced the same issue and the error occured during a code change. Everything was working before.
Somehow VSCode added `import e from 'express'`. this single line of code causes the issue.

Maybe that helps someone :)

**Comment by barbalex** [comment]
I installed react-xml-viewer. Then my app failed with errors mentioning safe-buffer. Following above comments I added buffer as dependency which solved the issue. Please declare this dependency.

**Comment by Akupsmee** [comment]
On vite react app installing
 `npm install safe-buffer`
 fixed it for me.

**Comment by Oscar-Serna** [comment]
> De repente me enfrenté al mismo problema y el error se produjo durante un cambio de código. Todo funcionaba antes. De alguna manera se agregó VSCode `import e from 'express'`. esta única línea de código causa el problema.
> 
> Quizás eso ayude a alguien :)

It helped me, thank you. For some reason { token } was imported from 'morgan'

**Comment by heisenberg-xx** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading 'from')
    at ../node_modules/safe-buffer/index.js (index.js:12:12)
    at __require2 (chunk-KEXKKQVW.js?v=39d72f9e:15:50)
    at ../node_modules/express/lib/utils.js (utils.js:15:14)
    at __require2 (chunk-KEXKKQVW.js?v=39d72f9e:15:50)
    at ../node_modules/express/lib/application.js (application.js:24:19)
    at __require2 (chunk-KEXKKQVW.js?v=39d72f9e:15:50)
    at ../node_modules/express/lib/express.js (express.js:18:13)
    at __require2 (chunk-KEXKKQVW.js?v=39d72f9e:15:50)
    at ../node_modules/express/index.js (index.js:11:18)
    at __require2 (chunk-KEXKKQVW.js?v=39d72f9e:15:50)
../node_modules/safe-buffer/index.js @ index.js:12
__require2 @ chunk-KEXKKQVW.js?v=39d72f9e:15
../node_modules/express/lib/utils.js @ utils.js:15
__require2 @ chunk-KEXKKQVW.js?v=39d72f9e:15
../node_modules/express/lib/application.js @ application.js:24
__require2 @ chunk-KEXKKQVW.js?v=39d72f9e:15
../node_modules/express/lib/express.js @ express.js:18
__require2 @ chunk-KEXKKQVW.js?v=39d72f9e:15
../node_modules/express/index.js @ index.js:11
__require2 @ chunk-KEXKKQVW.js?v=39d72f9e:15
(anonymous) @ index.js:11
Show 6 more frames
Show lessUnderstand this error
it happens suddenly what Can i do

**Comment by xcaptain** [comment]
in vite, `buffer` is the real imported module, no need to use `buffer.Buffer`, how to solve it?
