### ISSUE TITLE
Cannot read properties of undefined (reading 'from') at node_modules/safe-buffer/index.js

### ISSUE THREAD

**Issue by camellia-1H** [feross/safe-buffer#37]

**Comment by camellia-1H** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading 'from')
    at node_modules/safe-buffer/index.js (index.js:12:12)
    at __require (chunk-UXIASGQL.js?v=7ea3fefc:8:50)
    at node_modules/jws/lib/sign-stream.js (sign-stream.js:2:14)
    at __require (chunk-UXIASGQL.js?v=7ea3fefc:8:50)
    at node_modules/jws/index.js (index.js:2:18)
    at __require (chunk-UXIASGQL.js?v=7ea3fefc:8:50)
    at node_modules/jsonwebtoken/decode.js (decode.js:1:11)
    at __require (chunk-UXIASGQL.js?v=7ea3fefc:8:50)
    at node_modules/jsonwebtoken/index.js (index.js:2:11)
    at __require (chunk-UXIASGQL.js?v=7ea3fefc:8:50)

**Comment by camellia-1H** [comment]
I can't fix that -.-

**Comment by skaldebane** [comment]
i have the same issue!

**Comment by lennokiki** [comment]
same question, node version 16.20.0, vite
